### ISSUE TITLE
Android 11 proxy is invalid, can connect to google

### ISSUE THREAD

**Issue by mofada** [trojan-gfw/igniter#249] opened 2020-06-20 17:41 UTC
Android 11 proxy is invalid, can connect to google, but open google play without network

![screen](https://user-images.githubusercontent.com/22286246/85208020-bb11ea80-b35f-11ea-87e1-ca88f0748d3e.png)

![screen](https://user-images.githubusercontent.com/22286246/85208030-ce24ba80-b35f-11ea-96e8-d38c2f560833.png)

**Comment by mofada** [comment] 2020-06-20 17:45
https://developer.android.com/preview/behavior-changes-11

**Comment by mofada** [comment] 2020-06-20 17:45
My God, I'm dead, I can't upgrade or roll back now

**Comment by TchaikovDriver** [comment] 2020-06-22 03:03
Duplicate of #247

**Comment by mofada** [comment] 2020-06-22 05:42
My system is Android 11, and Android 10 was okay before. It has been like this since the upgrade yesterday

![image](https://user-images.githubusercontent.com/22286246/85252336-193ceb80-b48e-11ea-82d0-7ef3f9386a61.png)

**Comment by TchaikovDriver** [comment] 2020-06-22 13:32
Current target SDK version of Igniter is 28 rather than 29 (Android 10). Thus any behavior changes in Android 11 make no difference in Igniter.

**Comment by mofada** [comment] 2020-06-24 02:09
I still have a question, how to set proxy on windows terminal

**Comment by fuckgcdccp** [comment] 2020-06-24 06:33
连不上的你们把验证证书开关关掉就可以用了，不过不知道为什么这个突然用不了

**Comment by mofada** [comment] 2020-06-24 06:35
我重启手机就好了， 我还有另一个问题， 在Windows下怎么给命令行代理呢？

**Closed** 2020-07-01 09:01 UTC
