### ISSUE TITLE
快捷图标问题

### ISSUE THREAD

**Issue by hcnyf** [trojan-gfw/igniter#153] opened 2020-04-04 14:16 UTC
快捷图标只有在程序运行在前台时才有效，将程序后台运行时按下快捷图标是没反应的（等于目前这个快捷图标没有用）

**Comment by wongsyrone** [comment] 2020-04-04 14:50
@TchaikovDriver  Any idea?

**Comment by TchaikovDriver** [comment] 2020-04-06 09:25
> @TchaikovDriver Any idea?

I saw you made a commit that kill the tools process everytime user stops the service. That would cause the tile unavailable sometimes. But in most cases it still works well. I think the ROM's battery optimization may be the major reason that causes the problem. 


> 快捷图标只有在程序运行在前台时才有效，将程序后台运行时按下快捷图标是没反应的（等于目前这个快捷图标没有用）

Make sure you disable the battery optimization / startup restriction of Igniter. By the way, would you mind providing some information about your phone? For example, brand, model, ROM and Android version.

**Comment by hcnyf** [comment] 2020-04-06 11:23
[Screenrecorder-2020-04-06-19-08-20-360.zip](https://github.com/trojan-gfw/igniter/files/4437996/Screenrecorder-2020-04-06-19-08-20-360.zip)
手机：XiaoMi 10 Pro ，MIUI11 ，Android10 。我这里有录了个视频，可以看看（视频比较短操作的比较快，太大的文件无法上传到这里，不过应该能体现出来我描述的问题了）

**Comment by wongsyrone** [comment] 2020-04-06 12:16
> I saw you made a commit that kill the tools process everytime user stops the service.

Can we put ProxyService into another process?

**Comment by TchaikovDriver** [comment] 2020-04-06 12:59
> > I saw you made a commit that kill the tools process everytime user stops the service.
> 
> Can we put ProxyService into another process?

Of course, I will follow up this issue

**Comment by wongsyrone** [comment] 2020-04-06 13:50
Thanks. Killing the gomobile process is essential to make the whole app working properly. We haven't find a way to terminate Golang runtime completely without killing the process.

**Comment by TchaikovDriver** [comment] 2020-04-07 07:50
Hi hcnyf. Try the apk [here](https://github.com/TchaikovDriver/igniter/releases/tag/v0.1.0-pre-alpha21).
Be sure to disable all restrictions on Igniter, because this might be a manufacturer-specific issue (The tile works well on both of my phones). Please let me know whether the problem is solved in this release.

**Comment by hcnyf** [comment] 2020-04-07 08:02
> Hi hcnyf. Try the apk [here](https://github.com/TchaikovDriver/igniter/releases/tag/v0.1.0-pre-alpha21).
> Be sure to disable all restrictions on Igniter, because this might be a manufacturer-specific issue (The tile works well on both of my phones). Please let me know whether the problem is solved in this release.

Yes, this release solves the problem.

**Comment by TchaikovDriver** [comment] 2020-04-07 08:30
Thanks for your cooperation.

**Comment by wongsyrone** [comment] 2020-04-09 15:05
Should be fixed in the next release.

**Closed by wongsyrone** 2020-04-09 15:05 UTC
